UserLastName = input('Здравствуйте, введите свою фамилию ').capitalize()
UserFistName = input('Введи своё имя ').capitalize()
UserPatronymic = input('Введи своё отчество ').capitalize()
UserAddress = input('Введите свой адрес ').capitalize()
print(f'Здравствуйте, {UserLastName} {UserFistName} {UserPatronymic}.\nВаш заказ был отправлене по адресу {UserAddress}, согласно с полученными данными.')